spring:
  application:
    name: discoveryservice

server:
  port: 8761
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
